<?php

return [
    [
        'id' => 0,
        'name' => 'Основы Swift',
        'lessonsCompleted' => 3,
        'lessonsTotal' => 3,
        'deadline' => '2024-03-22',
        'estimatedTime' => 5400000,
        'performance' => 100,
    ],
    [
        'id' => 1,
        'name' => 'Разработка интерфейса в Xcode',
        'lessonsCompleted' => 5,
        'lessonsTotal' => 5,
        'deadline' => '2024-03-29',
        'estimatedTime' => 9000000,
        'performance' => 95,
    ],
    [
        'id' => 2,
        'name' => 'Swift и Objective-C: работа вместе',
        'lessonsCompleted' => 2,
        'lessonsTotal' => 2,
        'deadline' => '2024-04-05',
        'estimatedTime' => 3600000,
        'performance' => 98,
    ],
    [
        'id' => 3,
        'name' => 'Разработка iOS приложений с Swift',
        'lessonsCompleted' => 10,
        'lessonsTotal' => 12,
        'deadline' => '2024-04-19',
        'estimatedTime' => 14400000,
        'performance' => 93,
    ],
    [
        'id' => 4,
        'name' => 'Работа с базами данных и хранение данных в iOS',
        'lessonsCompleted' => 4,
        'lessonsTotal' => 4,
        'deadline' => '2024-04-26',
        'estimatedTime' => 7200000,
        'performance' => 97,
    ],
    [
        'id' => 5,
        'name' => 'SwiftUI и его возможности',
        'lessonsCompleted' => 6,
        'lessonsTotal' => 6,
        'deadline' => '2024-05-03',
        'estimatedTime' => 10800000,
        'performance' => 90,
    ],
    [
        'id' => 6,
        'name' => 'Разработка сетевых приложений на Swift',
        'lessonsCompleted' => 4,
        'lessonsTotal' => 5,
        'deadline' => '2024-05-10',
        'estimatedTime' => 7200000,
        'performance' => 92,
    ],
    [
        'id' => 7,
        'name' => 'Оптимизация и тестирование iOS приложений',
        'lessonsCompleted' => 3,
        'lessonsTotal' => 3,
        'deadline' => '2024-05-17',
        'estimatedTime' => 5400000,
        'performance' => 94,
    ]
];